#title: Distribution of observation types for a given user
#tags: observation-types,users


#DefaultView:PieChart
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>

SELECT ?label (COUNT(?observation_type) AS ?count) WHERE {
  ?site schema:creator "abbe"@sv ;
        schema:event ?event .

  ?event a ?observation_type .
  ?observation_type rdfs:label ?label .
}
GROUP BY ?label
ORDER BY DESC(?observation_type_count)
